import express from "express";
import cors from "cors";
import "dotenv/config"; 
import cookieParser from "cookie-parser";
import eventsRouter from "./routes/events";
import authRouter from "./routes/auth";
import swaggerUi from "swagger-ui-express";
import swaggerSpec from "./spec/swagger"; // generated by swagger-jsdoc

const app = express();

app.use(cors());
app.use(express.json());
app.use(cookieParser());

// Mount the router
app.use("/v1/events", eventsRouter);
app.use("/v1/auth", authRouter);

app.get("/health", (_req, res) => {
  res.status(200).json({ status: "ok", timestamp: new Date().toISOString() });
});

// Swagger docs
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerSpec));

//raw JSON spec
app.get('/api.json', (_req, res) => res.json(swaggerSpec));

export default app;