import express from "express";
import cors from "cors";
import "dotenv/config"; 
import cookieParser from "cookie-parser";
import {eventsRouter} from "./composition/events.wiring";
import {authRouter} from "./composition/auth.wiring";
import swaggerUi from "swagger-ui-express";
import swaggerSpec from "./spec/swagger"; // generated by swagger-jsdoc

const app = express();

app.use(express.json());
app.use(cors());
app.use(cookieParser());

//CORS: allow your Vite dev server to call the API
const CORS_ORIGIN = "http://localhost:5173";
const corsOptions = {
  origin: CORS_ORIGIN,
  methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
  allowedHeaders: ["Content-Type", "Authorization"],
  credentials: false, // you're not using cookies for access tokens
};
app.use(cors(corsOptions));
//app.options("*", cors(corsOptions)); // <-- crucial for Authorization preflight

// Mount the router
app.use("/v1/events", eventsRouter);
app.use("/v1/auth", authRouter);

//app.use(authRouter);

app.get("/health", (_req, res) => {
  res.status(200).json({ status: "ok", timestamp: new Date().toISOString() });
});

// Swagger docs
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerSpec));

//raw JSON spec
app.get('/api.json', (_req, res) => res.json(swaggerSpec));

export default app;