import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import cookieParser from "cookie-parser";
import eventsRouter from "./routes/events.ts";
import authRouter from "./routes/auth.ts";
import swaggerUi from "swagger-ui-express";
import swaggerSpec from "./spec/swagger.ts"; // generated by swagger-jsdoc



const app = express();
dotenv.config();

const PORT = process.env.PORT || 4000;
app.use(cors());
app.use(express.json());
app.use(cookieParser());

// Mount the router
app.use("/v1/events", eventsRouter);
app.use("/v1/auth", authRouter);

// Swagger docs
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerSpec));

//raw JSON spec
app.get('/api.json', (_req, res) => res.json(swaggerSpec));

// Start listening
app.listen(4000, () => console.log(`Server running on http://localhost:${PORT}")`));
console.log(`Swagger UI available at http://localhost:${PORT}/api-docs`);
