import express from "express";
import type { Request, Response, NextFunction } from "express";
import cors from "cors";
import "dotenv/config";
import cookieParser from "cookie-parser";
import {eventsRouter} from "./composition/events.wiring";
import {authRouter} from "./composition/auth.wiring";
import userProfileRouter from "./routes/userProfileRoutes"
import swaggerUi from "swagger-ui-express";
import swaggerSpec from "./spec/swagger"; // generated by swagger-jsdoc
import { AppError } from "./errors";

import path from "path"; //for picture uploads

const app = express();

app.use(express.json());

app.use(cookieParser());
app.use("/uploads", express.static(path.resolve("/uploads")));

//CORS: allow frontend server to call the backend server with cookies/refresh token
const CORS_ORIGINS = process.env.CORS_ORIGINS
  ? process.env.CORS_ORIGINS.split(",").map(s => s.trim())
  : ["http://localhost:5173"];

const corsOptions = {
  origin: CORS_ORIGINS,
  methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
  allowedHeaders: ["Content-Type", "Authorization"],
  credentials: true,
};
app.use(cors(corsOptions));

// Mount the router
app.use("/v1/events", eventsRouter);
app.use("/v1/auth", authRouter);
app.use(userProfileRouter);

//GLOBAL ERROR HANDLER
// When req.body parsing fails, route handler is never called
// it handles it and throws a custom 400 Invalid JSON paylod error
app.use((err: unknown, _req: Request, res: Response, _next: NextFunction) => {
  if (err instanceof SyntaxError && "body" in err) {
    return res.status(400).json({ message: "Invalid JSON payload" });
  }

  if (err instanceof AppError) {
    return res.status(err.status).json({ message: err.message });
  }

  //default
  console.error("Unhandled error:", err);
  return res.status(500).json({ message: "Internal server error" });
});

app.get("/health", (_req: Request, res: Response) => {
  res.status(200).json({ status: "ok", timestamp: new Date().toISOString() });
});

// Swagger docs
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerSpec));

//raw JSON spec
app.get("/api.json", (_req: Request, res: Response) => res.json(swaggerSpec));

export default app;